language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-19mode
gemfile:
  - gemfiles/activerecord_3.2.18.gemfile
  - gemfiles/activerecord_4.0.5.gemfile
  - gemfiles/activerecord_4.1.1.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: gem update --remote bundler
script:
  - bundle exec rake spec
